# Generated by Django 4.1.7 on 2023-03-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finpal_app', '0003_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default='equity', max_length=100),
        ),
    ]
